types_include = list(contact = c('contact', 'contact (ladder start)', 'contact (split)'), 
                     contact_mix = c('contact or contact-like', 
                                     'contact-like', 
                                     'contact or short contact or contact-like', 
                                     'contact or short contact',
                                     'contact-like or tjup', 
                                     'contactjup', 
                                     'contactkrr', 
                                     'contactortrruup',
                                     'short contact or contact'),
                     short_contact = c('short contact', 'tjup (short contact)', 'short contact (ladder)'),
                     growl = c('growl (upsweep)', 
                               'growl', 
                               'growl (kraa)', 
                               'growl (kree)', 
                               'growl (downsweep)', 
                               'growl (flight)', 
                               'growl (growlprr)', 
                               'growl (long)',
                               'growl (pfrr)', 
                               'prr'),
                     trruup = c('trruup', 
                                'krwiep'),
                     tjup = c('tjep', 
                              'tjup',
                              'tjup (ladder)',
                              'tjup (pip)',
                              'tjup (short contact)',
                              'tjup or contact or contact-like',
                              'tjup or contact-like',
                              'tjup or kaw',
                              'tjup or short contact',
                              'tjup or tut',
                              'tut'),
                     tja = c('tja', 
                             'tjagrrt', 
                             'tja (tjiep)', 
                             'tjarp', 
                             'trjap',
                             'trjarp',
                             'tje'),
                     alarm = c('alarm', 
                               'growl or alarm', 
                               'short alarm', 
                               'alarm (weird)'),
                     other = c('alarm_growl', 
                               'growl-contact', 
                               'growljup', 
                               'krk', 
                               'krkaw', 
                               'krwp', 
                               'mix',
                               'mixed', 
                               'pre', 
                               'tjujup',
                               'trr mix',
                               'trrkaw',
                               'tut or short contact',
                               'weird mix'),
                     kaw = c('kaw', 
                             'kew'),
                     # tonal_mix = c('dash', 
                     #               'dash (long)', 
                     #               'dash (up)', 
                     #               'pwep'),
                     frill = c('friep', 
                               'friwiep', 
                               'piep', 
                               'prjup', 
                               'prrfiew', 
                               'prriew',
                               'tuwiep'))
